// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUH82TniMwKft02QaDpjYZ9VkuA2F2J0Y',
    appId: '1:452426691626:web:2329163d119d8745c7ff53',
    messagingSenderId: '452426691626',
    projectId: 'flexcrew-1f436',
    authDomain: 'flexcrew-1f436.firebaseapp.com',
    storageBucket: 'flexcrew-1f436.firebasestorage.app',
    measurementId: 'G-MB0QCNSP9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV0rcOpTOpIGVWBctf_Fbo8kls0_Y8lr4',
    appId: '1:452426691626:android:764bd76b5a173979c7ff53',
    messagingSenderId: '452426691626',
    projectId: 'flexcrew-1f436',
    storageBucket: 'flexcrew-1f436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOS34TZCkK0wFua8Tv9y4Nu2WreKi_go4',
    appId: '1:452426691626:ios:a24d362a3bf66bdfc7ff53',
    messagingSenderId: '452426691626',
    projectId: 'flexcrew-1f436',
    storageBucket: 'flexcrew-1f436.firebasestorage.app',
    iosClientId: '452426691626-5d6q369nbvasd34hcs4ismq2j3mm4k6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOS34TZCkK0wFua8Tv9y4Nu2WreKi_go4',
    appId: '1:452426691626:ios:a24d362a3bf66bdfc7ff53',
    messagingSenderId: '452426691626',
    projectId: 'flexcrew-1f436',
    storageBucket: 'flexcrew-1f436.firebasestorage.app',
    iosClientId: '452426691626-5d6q369nbvasd34hcs4ismq2j3mm4k6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

}
